#!/usr/bin/env bash
#########################################
# HEJMO #################################
#########################################
#########################################
# a home directory system by Colin Dean #
# use at your own risk if you are not ^ #
# (c) 2015 Colin Dean                   #
# Unlicense <https://unlicense.org>     #
#########################################

## Track load time
current_time() {
  # macox date doesn't provide resolution greater than seconds
  # gdate isn't on the path yet when we need this but *almost*
  # assuredly perl is and it loads faster than anything else
  # https://superuser.com/a/713000
  perl -MTime::HiRes -e 'printf("%.0f\n",Time::HiRes::time()*1000)'
}
HEJMO_LOAD_START=$(current_time)

## Actually load stuff!

## Setup Hejmo base directories

#this should be a symlink
BASH_PROFILE_PHYSICAL="$(readlink "${BASH_SOURCE[0]}" )"
if [[ -z "${BASH_PROFILE_PHYSICAL}" ]]; then
  #but if it isn't
  BASH_PROFILE_PHYSICAL="${BASH_SOURCE[0]}"
fi
HEJMO_DOTFILE_DIR="$( cd "$( dirname "${BASH_PROFILE_PHYSICAL}" )" && pwd -P)"
# conveniently, this means that
export HEJMO="$( cd "${HEJMO_DOTFILE_DIR}/../" && pwd -P)"
HEJMO_BASH_PROFILE_DIR="${HEJMO}/bash_profile"

## Explicitly set some XDG directories

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"

## Explicitly set some early vars and aliases

alias rebash="source ${HOME}/.bash_profile"

### BENCHMARKING:
### Run this command to enable benchmarking output:
###     HEJMO_BENCH_BASH_PROFILE=1 bash -i

if [[ ${HEJMO_BENCH_BASH_PROFILE} ]]; then
  export HEJMO_BENCH_RESULTS="${HOME}/.hejmo_bench_results.txt"
  touch "${HEJMO_BENCH_RESULTS}"
  printf "" > "${HEJMO_BENCH_RESULTS}"
fi
for i in ${HEJMO_BASH_PROFILE_DIR}/*.sh; do
  if [[ ${HEJMO_BENCH_BASH_PROFILE} ]]; then
    # seconds
    TIMEFORMAT="%R = $i"
    { time . "$i" ; } 2>> "${HEJMO_BENCH_RESULTS}"
    unset TIMEFORMAT
  else
    . "$i"
  fi
done; unset i

HEJMO_LOAD_END=$(current_time)
export HEJMO_LOAD_TIME=$(echo "$HEJMO_LOAD_END - $HEJMO_LOAD_START" | bc )

if [[ ${HEJMO_BENCH_BASH_PROFILE} ]]; then
  >&2 echo "Hejmo Bash loading times, in user seconds"
  >&2 echo "------------------------"
  >&2 sort --numeric-sort --reverse "${HEJMO_BENCH_RESULTS}" | column --table --separator " = " --output-separator "\t"
  >&2 echo "------------------------------"
  >&2 echo "Total time: ${HEJMO_LOAD_TIME} milliseconds"
fi

############################################################
### ANYTHING added after here was added automatically      #
### and should be added to a file in ${HEJMO}/bash_profile #
############################################################

