#this should be a symlink
BASH_PROFILE_PHYSICAL="$(readlink "${BASH_SOURCE[0]}" )"
if [[ -z "${BASH_PROFILE_PHYSICAL}" ]]; then
  #but if it isn't
  BASH_PROFILE_PHYSICAL="${BASH_SOURCE[0]}"
fi
HEJMO_DOTFILE_DIR="$( cd "$( dirname "${BASH_PROFILE_PHYSICAL}" )" && pwd -P)"
# conveniently, this means that
export HEJMO="$( cd "${HEJMO_DOTFILE_DIR}/../" && pwd -P)"
HEJMO_BASH_PROFILE_DIR="${HEJMO}/bash_profile"

export XDG_CONFIG_HOME="${HOME}/.config"

source "${HEJMO_BASH_PROFILE_DIR}/00_path.sh"
source "${HEJMO_BASH_PROFILE_DIR}/00_ansi_color_helpers.sh"

export EDITOR=vim
alias vi='vim'
alias rebash="source ${HOME}/.bash_profile"

# string manipulation functions
source "${HEJMO_BASH_PROFILE_DIR}/01_strings.sh"
# directory navigation
source "${HEJMO_BASH_PROFILE_DIR}/02_navigation.sh"
# upsearch
source "${HEJMO_BASH_PROFILE_DIR}/02_upsearch.sh"
# configures ls and some useful aliases
source "${HEJMO_BASH_PROFILE_DIR}/50_ls.sh"
# ssh functions and aliases
source "${HEJMO_BASH_PROFILE_DIR}/99_ssh_aliases.sh"
# hashing functions and aliases
source "${HEJMO_BASH_PROFILE_DIR}/99_hashing.sh"

#export INTERNAL_GITHUB="" #set when setting up
#export INTERNAL_GITHUB_API_TOKEN=
#export INTERNAL_GITHUB_USER=
#export INTERNAL_EMAIL_USER=colindean

# prompt customization
source "${HEJMO_BASH_PROFILE_DIR}/99_prompt.sh"
# git functions and aliases
source "${HEJMO_BASH_PROFILE_DIR}/99_git.sh"
# gradle functions and aliases
source "${HEJMO_BASH_PROFILE_DIR}/99_gradle.sh"
# history management
source "${HEJMO_BASH_PROFILE_DIR}/99_history.sh"
# manpage colors
source "${HEJMO_BASH_PROFILE_DIR}/99_man_colors.sh"
# chromecasting
source "${HEJMO_BASH_PROFILE_DIR}/99_chromecast.sh"
# bat
source "${HEJMO_BASH_PROFILE_DIR}/99_bat.sh"

[[ -s "$HOME/.env.local" ]] && source "$HOME/.env.local"

# bash completions
source "${HEJMO_BASH_PROFILE_DIR}/99_completions.sh"

if [[ -z $NO_RVM ]]; then
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
fi

if [[ -z $NO_CHRUBY ]]; then
  chruby_share="$(brew --prefix chruby)/share/chruby"
  [[ -s "${chruby_share}/chruby.sh" ]] && . "${chruby_share}/chruby.sh"
  [[ -s "${chruby_share}/auto.sh" ]] && . "${chruby_share}/auto.sh"
fi

# added by travis gem
[[ -f "$HOME/.travis/travis.sh" ]] && . "$HOME/.travis/travis.sh"
#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "$HOME/.gvm/bin/gvm-init.sh" ]] && source "$HOME/.gvm/bin/gvm-init.sh"
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
source "$HOME/.cargo/env"
export PATH="$HOME/.cargo/bin:$PATH"
