#!/usr/bin/env bash

_e() { [[ -n "${DEBUG_COMPLETIONS}" ]] && echo "$1" >> "${HOME}/completions.log"; }

_main() {
  local i=1 cmd


  _e "comp_words = ${COMP_WORDS[*]}"

  # find the subcommand
  while [[ "$i" -lt "$COMP_CWORD" ]]
  do
    local s="${COMP_WORDS[i]}"
    case "$s" in
      -*) ;;
      *)
        cmd="$s"
        break
        ;;
    esac
    (( i++ ))
  done

  _e "comp_cword = ${COMD_CWORD}"
  _e "cmd = $cmd"

  if [[ "$i" -eq "$COMP_CWORD" ]]
  then
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local nocolon

    _get_comp_words_by_ref -n : -c nocolon

    _e "cur = $cur"
    _e "nocolon = ${nocolon}"

    COMPREPLY=($(compgen -W "$(t actions)" -- "$cur"))
    _e "COMPREPLY = ${COMPREPLY[*]}"

    return # return early if we're still completing the 'current' command
  fi

  # we've completed the 'current' command and now need to call the next completion function
  # subcommands have their own completion functions
  case "$cmd" in
    sw|switch|"in") _list_projects ;;
    start) _list_projects;;
    log) _list_projects;;
    *)          ;;
  esac
}

_list_projects ()
{
  local cur="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=($(compgen -W "$(t projects)" -- "$cur"))
}
export COMP_WORDBREAKS="${COMP_WORDBREAKS//:}"
complete -o bashdefault -F _main t
