#!/usr/bin/env bash

case "$(uname -s)" in
  "Darwin")
    sudo dscacheutil -flushcache && \
      sudo killall -HUP mDNSResponder
    ;;
  *)
    echo "$(uname -s) not yet supported in $0"
    ;;
esac
