#!/usr/bin/env sh

git log --reverse --pretty=format:'%H%x00%aN <%aE>%x00%cn <%cE>%x00%aI%x00%s%x00' |
	jq -R -s '[split("\n")[:-1] | map(split("\u0000")) | .[] | {
    "commit": .[0],
    "author": .[1],
    "committer": .[2],
    "date": .[3],
    "subject": .[4],
  }]'
