#!/usr/bin/env bash

set -eu -o pipefail
# based on https://stackoverflow.com/a/73879664/204052

if command -v ggrep >/dev/null; then
	FALLBACK_GREP="ggrep"
else
	FALLBACK_GREP="grep"
fi
GREP="${GREP:-${FALLBACK_GREP}}"

get_netrc_entry() {
	machine_entry=$(tr '\n' ' ' <~/.netrc | "${GREP}" -oP "(?<=machine ${1//./\\.} ).*?(?=( machine)|$)")
	"${GREP}" -oP '(?<=login ).*?(?=\s|$)' <<<"${machine_entry}"
	"${GREP}" -oP '(?<=password ).*?(?=\s|$)' <<<"${machine_entry}"
}

usage() {
	printf "Usage: %s get [login|user|username|password|pass|secret] <machine>\n" "${0}" >&2
}

# shellcheck disable=SC2068
case "${1}" in
get)
	shift
	case "${1}" in
	login | user | username)
		shift
		get_netrc_entry $@ | head -n 1
		;;
	password | pass | secret)
		shift
		get_netrc_entry $@ | tail -n 1
		;;
	*)
		get_netrc_entry $@
		;;

	esac
	;;
*)
	usage
	;;
esac
