#!/bin/bash

EXTRA_VIM_OPTIONS="+qall"

VIM=$(command -v vim)
if [[ -z "${VIM}" ]]; then
  echo "Vim not installed. Can't do much without it."
  exit 1
fi

usage() {
  echo "plug wrapper usage:"
  echo "$0 install|update|upgrade|status|clean|update-plug"
}

case $1 in
  install )
    "${VIM}" +PlugInstall "${EXTRA_VIM_OPTIONS}"
    ;;
  update )
    "${VIM}" +PlugUpdate "${EXTRA_VIM_OPTIONS}"
    ;;
  upgrade )
    "${VIM}" +PlugUpgrade "${EXTRA_VIM_OPTIONS}"
    ;;
  status )
    "${VIM}" +PlugStatus #"${EXTRA_VIM_OPTIONS}"
    ;;
  clean )
    "${VIM}" +PlugClean "${EXTRA_VIM_OPTIONS}"
    ;;
  update-plug )
    curl --progress-bar -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    ;;
  -h | --help)
     usage
     ;;
  * )
    echo "Unknown option."
    usage
    exit 1
    ;;
esac
