#!/bin/bash
NEW="${1}"

if [[ -z "${NEW}" ]]; then
  >&2 echo "Usage: $0 new-hostname"
  exit 1
fi

if [[ "Darwin" == "$(uname -s)" ]]; then
  sudo scutil --set ComputerName "${NEW}"
  sudo scutil --set HostName "${NEW}"
  sudo scutil --set LocalHostName "${NEW}"
else
  sudo hostname "${NEW}"
fi
  hostname -f
