#!/usr/bin/env bash
VNC="/System/Library/CoreServices/Applications/Screen Sharing.app/Contents/MacOS/Screen Sharing"

internal_hostname=$1

if [[ -z ${internal_hostname} ]]; then
  echo "Provide a hostname."
  exit 1
fi

ssh -n admin@blackridge.dyn.cad.cx -L "5901:${internal_hostname}:5900" &

sshpid=$!
echo "Waiting for connection..."

sleep 5


"${VNC}" "${internal_hostname}"

kill $sshpid
