#!/usr/bin/env bash
# shellcheck disable=SC2312
# Shows what user is used for docker login
# currently only for macOS
jq -r \
	'if (.credsStore == "osxkeychain") then (.auths | keys) else [] end | .[]' \
	"${HOME}/.docker/config.json" |
	docker-credential-osxkeychain get |
	jq '{"url": .ServerURL, "user": .Username}'
