#!/usr/bin/env bash

OS_TYPE="$(uname -s)"
case "${OS_TYPE}" in
  "Darwin")
    sudo dscacheutil -flushcache && \
      sudo killall -HUP mDNSResponder
    ;;
  *)
    echo "${OS_TYPE} not yet supported in $0"
    ;;
esac
