#!/usr/bin/env bash

# TODO: add Linux support (e.g. `sudo systemd-resolve --flush-caches` or `sudo resolvectl flush-caches`)

OS_TYPE="$(uname -s)"
case "${OS_TYPE}" in
  "Darwin")
    sudo dscacheutil -flushcache && \
      sudo killall -HUP mDNSResponder
    ;;
  *)
    echo "${OS_TYPE} not yet supported in $0"
    ;;
esac
