#!/bin/bash
USAGE='[--cached] [<rev-list-options>...]

Show file size changes between two commits or the index and a commit.'

usage() {
  >&2 echo "${USAGE}"
}

# shellcheck source=/dev/null disable=SC2312
. "$(git --exec-path)/git-sh-setup"
args=$(git rev-parse --sq "$@")
[[ -n "${args}" ]] || usage
cmd="diff-tree -r"
[[ ${args} =~ "--cached" ]] && cmd="diff-index"
# shellcheck disable=SC2312
eval "git ${cmd} ${args}" | {
  total=0
  while read -r A B C D M P
  do
    case ${M} in
      M) bytes=$(( $(git cat-file -s "${D}") - $(git cat-file -s "${C}") )) ;;
      A) bytes=$(git cat-file -s "${D}") ;;
      D) bytes=-$(git cat-file -s "${C}") ;;
      *)
        echo >&2 "warning: unhandled mode ${M} in \"${A} ${B} ${C} ${D} ${M} ${P}\""
        continue
        ;;
    esac
    total=$(( total + bytes ))
    printf '%d\t%s\n' "${bytes}" "${P}"
  done
  echo total "${total}"
}
