#!/usr/bin/env bash

# dig +short _submission._tcp.cad.cx srv
# 0 1 587 smtp.fastmail.com.

DOMAIN="${1}"

if [[ -z "${DOMAIN}" ]]; then
  >&2 echo -e "Usage:\n\t$(basename "$0") domain.tld"
  exit 1
fi

IMAP="_imap._tcp.${DOMAIN}"
IMAPS="_imaps._tcp.${DOMAIN}"
POP3="_pop3._tcp.${DOMAIN}"
POP3S="_pop3s._tcp.${DOMAIN}"
SMTP="_submission._tcp.${DOMAIN}"
MX="${DOMAIN}"

srv() {
  dig +short "${1}" srv
}

mx() {
  dig +short "${1}" mx
}


# shellcheck disable=SC2312
IMAP_RESULT="$(srv "${IMAP}" | head -n 1)"
# shellcheck disable=SC2312
IMAPS_RESULT="$(srv "${IMAPS}" | head -n 1)"
# shellcheck disable=SC2312
POP3_RESULT="$(srv "${POP3}" | head -n 1)"
# shellcheck disable=SC2312
POP3S_RESULT="$(srv "${POP3S}" | head -n 1)"
# shellcheck disable=SC2312
SMTP_RESULT="$(srv "${SMTP}" | head -n 1)"
# shellcheck disable=SC2312
MX_RESULT="$(mx "${MX}" | head -n 1)"


column -t -s "~" <<MSG
Domain~${DOMAIN}
IMAP~${IMAP_RESULT:-<<none>>}
IMAPS~${IMAPS_RESULT:-<<none>>}
POP3~${POP3_RESULT:-<<none>>}
POP3S~${POP3S_RESULT:-<<none>>}
SMTP~${SMTP_RESULT:-<<none>>}
MX~${MX_RESULT:-<<none>>}
MSG
