#!/usr/bin/env bash

#man -t ledger | ps2pdf - /tmp/man-ledger.pdf && open /tmp/man-ledger.pdf
MAN_ARGS=("$@")
IDENTIFIER="${MAN_ARGS[*]}"
IDENTIFIER="${IDENTIFIER// /}"

PDF_FILENAME="man-${IDENTIFIER}.pdf"
PDF_TARGET="${TMPDIR}${PDF_FILENAME}"

if [[ -f "${PDF_TARGET}" ]]; then
	open "${PDF_TARGET}"
	exit 0
fi

MAN_PATH="$(command -v man)"
if [[ -z "${MAN_PATH}" ]]; then
	>&2 echo "No man found, are manpages actually installed?"
	exit 1
fi

PS2PDF_PATH="$(command -v ps2pdf)"
if [[ -z "${PS2PDF_PATH}" ]]; then
	>&2 echo "No ps2pdf found, ensure that it is installed."
	exit 2
fi

# ensure it exists first
# shellcheck disable=SC2034  # MANPAGE_PATH is used for validation
MANPAGE_PATH="$("${MAN_PATH}" --path "${MAN_ARGS[@]}")"
manpath_path_exit=$?
if [[ ${manpath_path_exit} -ne 0 ]]; then
	#>&2 echo "No manpage available for '${MAN_ARGS}'."
	exit "${manpath_path_exit}"
fi

# -t outputs postscript using groff, see `man man` for details.
# ps2pdf - - means convert stdin to pdf and output on stdout
# shellcheck disable=SC2312
"${MAN_PATH}" -t "${MAN_ARGS[@]}" | "${PS2PDF_PATH}" - - >"${PDF_TARGET}"

if [[ -f "${PDF_TARGET}" ]]; then
	open "${PDF_TARGET}"
	exit 0
else
	>&2 echo "${PDF_TARGET} does not exist, something went wrong."
	exit 4
fi
