#!/usr/bin/env bash

usage() {
	echo "Get the package files available for a PyPI package"
	echo "usage: $0 package [version]" >&2
}

get_latest_version() {
	local package="${1}"
	# shellcheck disable=SC2312
	curl -s -L "https://pypi.python.org/pypi/${package}/json" | jq -r '.releases | keys | .[]' | sort -V | tail -n 1
}

require_command() {
	if ! command -v "${1}" >/dev/null; then
		echo "Needs ${1}, install it!" >&2
		exit 1
	fi
}

require_command curl
require_command jq
require_command sort
require_command tail

package="${1}"

if [[ -z "${package}" ]]; then
	usage
fi

printf "Getting packages for %s" "${package}" >&2

version="${2:-$(get_latest_version "${package}")}"

printf " v%s\n" "${version}" >&2

# shellcheck disable=SC2312
curl -s -L "https://pypi.python.org/pypi/${package}/json" | jq -r --arg release "${version}" '.releases[$release].[].filename' | sort -V
