#!/bin/bash
if [[ -z "${1}" ]]; then
	echo "You must specify a size in megabytes."
  exit 1
fi
size=$1
# multiply by 2048 because the size we need to pass is based on
# 512 byte sectors. Divide the size in _bytes_ by 512. We're passing
# the size in megabytes, so math means 2048.
realsize=$(echo "${size} * 2048" | bc)

name="${2:-ramdisk}"

echo "Creating a ${size} MB (${realsize}) ramdisk at /Volumes/${name}..."

# shellcheck disable=SC2312
volume=$(hdiutil attach -nomount "ram://${realsize}" | tr -d '[:space:]')
echo "Ramdisk attached at ${volume}"

# the above seems to take a moment to actually take effect.
sleep 1

diskutil erasevolume HFS+ "${name}" "${volume}"
echo "Ramdisk at ${volume} formatted HFS+ as ${name}"

echo "Unmount with: hdiutil eject ${volume}"
echo "Remember, everything will go away the moment it is ejected!"
