#!/bin/bash
if [ -z $1 ]; then
	echo "You must specify a size in megabytes."
  exit 1
fi
size = $1
realsize = `echo ${size} * 2048 | bc`

name = "ramdisk"

if [ -n $2 ]; then
	name = "${2}"
fi


diskutil erasevolume HFS+ "${name}" `hdiutil attach -nomount ram://${realsize}`
