#!/usr/bin/env bash
EFFECTIVE_POM="${1:-target/effective-pom.xml}"
>&2 echo "Getting dependencies in group:artifact:version format from effective POM to be output in ${EFFECTIVE_POM}"
if [[ "${EFFECTIVE_POM}" = "pom.xml" ]]; then
	>&2 echo "Not overwriting pom.xml, that'd be a really bad idea!"
	exit 1
fi

mvn --quiet help:effective-pom "-Doutput=${EFFECTIVE_POM}"

xmlstarlet select --omit-decl --noblanks --text -N "pom=http://maven.apache.org/POM/4.0.0" \
	--template \
	--match '/pom:project/pom:dependencies/pom:dependency[pom:scope/text()="compile" or pom:scope/text()="runtime"]' \
	-v "concat(pom:groupId, ':', pom:artifactId, ':', pom:version)" \
	--if "position() != last()" \
	--output ',' \
	"${EFFECTIVE_POM}"
