#!/usr/bin/env sh

VIDEO_COEFF="${1}"
INPUT="${2}"
OUTPUT="${3}"

if [ -z "${VIDEO_COEFF}" ] || [ -z "${INPUT}" ]; then
	>&2 echo "Usage: ${0} coefficient input output"
	exit 1
fi

AUDIO_COEFF="$(echo "scale=10;1 / ${VIDEO_COEFF}" | bc)"

ffmpeg -i "${INPUT}" -vf "setpts=${VIDEO_COEFF}*PTS" -filter:a "atempo=${AUDIO_COEFF}" "${OUTPUT}"
