#!/bin/sh
OPTIONS=$(vagrant ssh-config | awk -v ORS=' ' '{print "-o " $1 "=" $2}')
if [ -n "${VDEBUG}" ]; then
  echo "${OPTIONS}" "$@"
fi
scp "${OPTIONS}" "$@" || echo "Transfer failed. Did you use 'default:' as the target?"
