#!/bin/bash

EXTRA_VIM_OPTIONS="+qall"

VIM=$(command -v vim)
if [[ -z "${VIM}" ]]; then
  echo "Vim not installed. Can't do much without it."
  exit 1
fi

usage() {
  echo "vundle wrapper usage:"
  echo "$0 install|update|list|clean|search [search terms]"
}

case $1 in
  install )
    "${VIM}" +PluginInstall "${EXTRA_VIM_OPTIONS}"
    ;;
  update )
    "${VIM}" +PluginUpdate "${EXTRA_VIM_OPTIONS}"
    ;;
  list )
    "${VIM}" +PluginList "${EXTRA_VIM_OPTIONS}"
    ;;
  clean )
    "${VIM}" +PluginClean "${EXTRA_VIM_OPTIONS}"
    ;;
  search )
    "${VIM}" +PluginSearch $2 $3 $4 $5 $6 $7 $8 $9 "${EXTRA_VIM_OPTIONS}"
    ;;
  -h | --help)
     usage
     ;;
  * )
    echo "Unknown option."
    usage
    exit 1
    ;;
esac
