#!/usr/bin/env bash

ssid_cmd="ssid"
ssid_cmd="$(command -v ssid)"
if [[ -z "${ssid_cmd}" ]]; then
  >&2 echo "ssid retrieval command not found. Without an SSID, I cannot tell where I am."
  exit 1
fi

ssid="$(ssid)"

case "${ssid}" in
  "Code & Supply") echo "[37;1mC[31;1m&[37;1mS[0m";;
  "blackridge.cad.cx") echo "🏠";;
  "") echo "Not connected to WiFi, so ¯\\_(ツ)_/¯";;
  *) echo "${ssid}";;
esac
