#!/usr/bin/env bash

# YEP="_a__r" NOPE=etyipsdglcbn MUST=""

PATTERN="${1}"
EXCLUDE="${2}"
INCLUDE="${3}"

if command -v rg >/dev/null; then
  GREP="${GREP:-rg}"
else
  GREP="${GREP:-grep}"
fi

if [[ ! "${PATTERN}" =~ "_" ]]; then
  echo "First arg must have _ in it to indicate blanks, or you're already done!"
  echo "Pass excludes as second arg and includes as third."
  exit 1
fi


echo -n "Looking for words fitting [${PATTERN}]"
if [[ -n "${EXCLUDE}" ]]; then
  echo -n " and not having [${EXCLUDE}]"
fi
if [[ -n "${INCLUDE}" ]]; then
  echo -n " and having [${INCLUDE}]"
fi

echo

NOT="[^${PATTERN//_/}${EXCLUDE}]"

REGEX="^${PATTERN//_/${NOT}}$"

if [[ -n "${DEBUG}" ]]; then
  echo "with regex: ${REGEX}"
fi

echo "Candidates:"
"${GREP}" "${REGEX}" /usr/share/dict/words | "${GREP}" "${INCLUDE:-}"
