#!/usr/bin/env bash

PATTERN="${1}"
EXCLUDE="${2}"
INCLUDE="${3}"

log() {
  >&2 echo "${@}"
}

if command -v rg >/dev/null; then
  GREP="${GREP:-rg}"
else
  GREP="${GREP:-grep}"
fi

if [[ ! "${PATTERN}" =~ "_" ]]; then
  log "First arg must have _ in it to indicate blanks, or you're already done!"
  log "Pass excludes as second arg and includes as third."
  exit 1
fi


log "$(printf \
  "Looking for words fitting [%s] excluding [%s] including [%s]" \
  "${PATTERN}" \
  "${EXCLUDE}" \
  "${INCLUDE}")"

if [[ -n "${EXCLUDE}" ]] || (echo "${PATTERN}" | grep -vq '\w') ; then
  NOT="[^${PATTERN//_/}${EXCLUDE}]"
fi

REGEX="^${PATTERN//_/${NOT:-'\w'}}$"

if [[ -n "${DEBUG}" ]]; then
  log "with regex: ${REGEX}"
fi

log "Candidates:"
# shellcheck disable=SC2312
"${GREP}" "${REGEX}" /usr/share/dict/words | "${GREP}" "${INCLUDE:-}"
