#!/usr/bin/env ruby
require 'json'
require 'yaml'

def yaml_as_ruby(data)
  YAML.parse(data).to_ruby
end

file = ARGV.pop
data = if file == '-'
         STDIN.read
       else
         File.read(file)
       end

unless ENV['PRETTY']
  puts yaml_as_ruby(data).to_json
else
  puts JSON.pretty_generate(yaml_as_ruby(data))
end
